server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


spring:
  cloud:
    gateway:
      routes:
        - id: consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/consumer-service/**

        - id: goods-service
          uri: lb://goods-service
          predicates:
            - Path=/goods-service/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
