server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


spring:
  cloud:
    gateway:
      routes:
        - id: consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/consumer-service/**

        - id: goods-service
          uri: lb://goods-service
          predicates:
            - Path=/goods-service/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Enables DEBUG level logging for Gateway routes
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG  # Log request details
    org.springframework.cloud.gateway.filter: DEBUG  # Detailed logs for filters in the Gateway
    org.springframework.cloud.gateway.route: DEBUG
