server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


spring:
  cloud:
    gateway:
      routes:
        - id: CONSUMER-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/consumer-service/**

        - id: GOODS-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/goods-service/**

        - id: ORDER-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Enables DEBUG level logging for Gateway routes
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG  # Log request details
    org.springframework.cloud.gateway.filter: DEBUG  # Detailed logs for filters in the Gateway
    org.springframework.cloud.gateway.route: DEBUG
