server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


#DB properties
spring:
  data:
    mongodb:
      uri: mongodb+srv://arun:SunJava123@arun.l7wpi.mongodb.net/?retryWrites=true&w=majority&appName=arun
      database: goods-service
