server:
  port: 8088

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arunachala-001/MongoDB-Microservice.git
          search-paths: config-repo
          default-label: main
          clone-on-start: true

logging:
  level:
    org.springframework.cloud.config: DEBUG

